config_form.settings:
  path: '/admin/config/user-info'
  defaults:
    _form: '\Drupal\config_form\Form\UserConfigForm'
    _title: 'User Information Configuration'
  requirements:
    _permission: 'Administer site configuration'
