# Schema for the configuration files of the Movie budget module.
movie_budget.settings:
  type: config_object
  label: 'Movie budget settings'
  mapping:
    example:
      type: string
      label: 'Budget'
